# Generated by Django 2.2.11 on 2020-03-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200318_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Autorin',
            new_name='author',
        ),
    ]
